runtime: nodejs10
service: test-api-gateway
env_variables:
  HISTORY_URL: ''
  MAILER_URL: ''
  DEVICE_CONTROL_URL: ''
  USER_URL: ''
  JWT_KEY: ''
  GOOGLE_CLIENT_SECRET: ''
  GOOGLE_CLIENT_ID: ''
  PROJECT_ID: ''
