name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Pull Request size labeler
    steps:
      - uses: CodelyTV/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '2'
          s_max_size: '5'
          m_max_size: '10'
          l_max_size: '20'
          fail_if_xl: 'false'
